name: Check Swagger API

on:
  schedule:
    - cron: '35 17 */4 * 4'

jobs:
  e2e_tests:
    name: E2E test
    env:
      CI: true

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest # or "latest", "canary", <sha>

      # https://github.com/microsoft/TypeScript/wiki/Node-Target-Mapping
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install dependencies
        run: bun install

      - name: E2E test
        run: bun test:e2e:prod
